### ISSUE TITLE
returning a list of graphs is over-designing...

### ISSUE THREAD

**Issue by dimpase** [rschrecker/MuzychukProject#3]
it is also not necessary; if you call right random functions they will generate new random things (after setting the random seed once), so you can simply call the function in the loop!

**Comment by rschrecker** [comment]
Well the idea was to improve speed when generating a larger number of examples - it appears for example that AffineGeometryDesign is quite slow and there's no need to repeat it. I can take it out if you'd prefer though, it is rather ugly

**Comment by dimpase** [comment]
You can make the design an extra (optional) parameter, especially as in general it need not be a design of this particular type (unless I recall wrongly).

**Comment by rschrecker** [comment]
For S6 only affine designs are used (if I understand the paper correctly). I've switched to ProjectiveGeometryDesign as you suggested, its much faster.

**Comment by dimpase** [comment]
Affine designs need not be coming from the affine spaces over finite fields (this is actually mentioned in Muzychuk's paper, at the top of p.172). It seems that these other examples with r=1  are providing "interesting" graphs in S6.
